serverIndex: -1
# Available: BOX, TDM
serverType: TDM
minPlayers: 4

resourcePack:
  url: https://drive.google.com/uc?export=download&id=1rJPGacKOuMa-OqXnxSIl2z5qZf3fVEBY
  hash: A97B4069B1B40DB03B1695DE027F70FB652C6FA5

pvpLocation: world -94 91 32 -90 0

rankingHolograms:
  totalKills: world -147.5 7.5 -318

safeZone:
  ==: fr.olympa.api.spigot.region.shapes.ExpandedCuboid
  world: "world"
  xMin: -220
  zMin: -340
  xMax: -75
  zMax: -220
 
killbox:
  ==: fr.olympa.api.spigot.region.shapes.Cuboid
  world: "world"
  xMin: -168
  yMin: 55
  zMin: 59
  xMax: -139
  yMax: 80
  zMax: 171